apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: anomaly-ai
  labels:
    app: anomaly-ai
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: anomaly-ai
  endpoints:
    - port: http
      path: /metrics
      interval: 15s