apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: edge-gateway
  labels:
    app: edge-gateway
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: edge-gateway
  endpoints:
    - port: http
      path: /metrics
      interval: 15s