image:
  repository: mongo
  tag: "7.0"
  pullPolicy: IfNotPresent

service:
  port: 27017

storage:
  size: 1Gi

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 1Gi