apiVersion: v1
kind: Service
metadata:
  name: remediation-controller
  labels:
    app: remediation-controller
spec:
  type: ClusterIP
  selector:
    app: remediation-controller
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP