apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-api
  labels:
    app: catalog-api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: catalog-api
  template:
    metadata:
      labels:
        app: catalog-api
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001          # the appuser we created in the Go Dockerfile
        fsGroup: 10001
      containers:
        - name: catalog-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: MONGO_URI
              value: "{{ .Values.config.mongoUri }}"
            - name: MONGO_DB
              value: "{{ .Values.config.mongoDb }}"
          startupProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.port }}
            periodSeconds: 5
            failureThreshold: 20
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.port }}
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: {{ .Values.service.port }}
            periodSeconds: 10
            failureThreshold: 3
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]